import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Layout from "./_featured/layout/Layout";
import Cursor from "./_components/Cursor/Cursor";
import { RecoilRoot } from "recoil";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout>
          <Cursor />
          {children}
        </Layout>
      </body>
    </html>
  );
}
